version: '3'

services:
  api:
    build: ./api
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db-mongo:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  db-mongo:
    driver: local
